In [18]:
import numpy as np
import pandas as pd
from scipy.stats import entropy

dataset_users = pd.read_csv('data/rating_5000_cls_hc_10core_iterative.csv', delimiter='\t', header=None)
dataset_features = pd.read_csv('data/loan_feature_df_hc_10core.csv',header=None)

                                 user_id  loan_id  rating
0       00043ad3146f033d4bf1beb502fa6e09       41     3.0
1       00043ad3146f033d4bf1beb502fa6e09       60     3.0
2       00043ad3146f033d4bf1beb502fa6e09      175     3.0
3       00043ad3146f033d4bf1beb502fa6e09      191     3.0
4       00043ad3146f033d4bf1beb502fa6e09      265     3.0
...                                  ...      ...     ...
110366  fff15c0cb55b7bb93d4822411d03bc9c     1626     3.0
110367  fff15c0cb55b7bb93d4822411d03bc9c     2079     3.0
110368  fff15c0cb55b7bb93d4822411d03bc9c     3359     3.0
110369  fff15c0cb55b7bb93d4822411d03bc9c     4590     3.0
110370  fff15c0cb55b7bb93d4822411d03bc9c     4601     3.0

[110371 rows x 3 columns]

In [19]:
#set header names
dataset_users.columns = ['user_id', 'loan_id', 'rating']
dataset_features.columns = ['loan_id', 'feature_id', 'feature_value']

In [21]:
#merge the two datasets on loan_id
dataset_merged = pd.merge(dataset_users, dataset_features, on='loan_id')

unique_features = dataset_merged['feature_id'].unique()

n_unique_features = len(unique_features)

In [22]:
dataset_merged

,user_id,loan_id,rating,feature_id,feature_value
0,00043ad3146f033d4bf1beb502fa6e09,41,3.0,ACTIVITY_Retail,1
1,00043ad3146f033d4bf1beb502fa6e09,41,3.0,GENDER_F,1
2,00043ad3146f033d4bf1beb502fa6e09,41,3.0,COUNTRY_Colombia,1
3,00043ad3146f033d4bf1beb502fa6e09,41,3.0,loan_buck_1,1
4,00043ad3146f033d4bf1beb502fa6e09,41,3.0,pfr_buck_3,1
...,...,...,...,...,...
551790,fb315ee357ecd1461de5e56dcaf211c6,4843,3.0,ACTIVITY_Farming,1
551791,fb315ee357ecd1461de5e56dcaf211c6,4843,3.0,GENDER_M,1
551792,fb315ee357ecd1461de5e56dcaf211c6,4843,3.0,COUNTRY_low_pfr,1
551793,fb315ee357ecd1461de5e56dcaf211c6,4843,3.0,loan_buck_3,1
551794,fb315ee357ecd1461de5e56dcaf211c6,4843,3.0,pfr_buck_3,1

In [23]:
if n_unique_features <= 1:
    dataset_merged['entropy'] = 0
else:
    #create a pivot table
    pivot_table = pd.pivot_table(dataset_merged, values='feature_value', index=['user_id', 'loan_id', 'rating'], columns=['feature_id'], aggfunc=np.sum)
    pivot_table = pivot_table.fillna(0)
    pivot_table = pivot_table.applymap(lambda x: 1 if x > 0 else 0)
    #calculate entropy
    dataset_merged['entropy'] = pivot_table.apply(lambda x: entropy(x), axis=1)

TypeError: incompatible index of inserted column with frame index

In [ ]:
for user in users:
    count loans funded - array of 0's with that length
    for feature in features:
        count loans with that feature 
        replace that many 0's with 1's 
        add a 1 to array
        calculate entropy of array
        append userid, feature, entropy

In [ ]:
# Initialize an empty list to store the results
results = []

for user in dataset_merged['user_id'].unique():
    user_data = dataset_merged[dataset_merged['user_id'] == user]
    count_loans_funded = np.zeros(len(unique_features))
    
    for idx, feature in enumerate(unique_features):
        count_loans_with_feature = len(user_data[user_data['feature_id'] == feature])
        count_loans_funded[:count_loans_with_feature] = 1
        
        entropy_val = entropy(count_loans_funded)
        
        results.append([user, feature, entropy_val])

# Create a new DataFrame from the results list
results_df = pd.DataFrame(results, columns=['user_id', 'feature_id', 'entropy'])

print(results_df.head())